version: '3.7'

services:

  frontend:
    container_name: frontend
    build:
        context: .
        dockerfile: Dockerfile
    stdin_open: true
    volumes:
        - '.:/usr/app'
        - '/app/node_modules'
    ports:
        - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn start
        