version: '3.7'

services:
  app:
    container_name: react-app
    build:
        context: .
        dockerfile: Dockerfile
    command: yarn start
    volumes:
        - '.:/app'
        - '/app/node_modules'
    ports:
        - '3000:3000'
    environment:
        - NODE_ENV=development
        