version: '3.7'

services:
  api:
    container_name: node-api
    build:
        context: ./backend
        dockerfile: Dockerfile
    command: yarn dev
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
  
  app:
    container_name: react-app
    build:
        context: ./frontend
        dockerfile: Dockerfile
    command: yarn start
    volumes:
        - '.:/app'
        - '/app/node_modules'
    ports:
        - '3000:3000'
    environment:
        - NODE_ENV=development