version: '3.7'

services:
  api:
    container_name: oop-api-message
    image: maiconloure/nodepoo
    command: yarn dev
    ports:
      - "3333:3333"
    volumes:
      - ./app
  
  web:
    container_name: oop-react-message
    image: react-docker-app
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true