version: '3.7'

services:
  api:
    container_name: node-api
    build:
        context: ./api
        dockerfile: Dockerfile
    command: yarn dev
    ports:
      - "3333:3333"
    volumes:
      - ./api:/usr/app

  frontend:
    container_name: frontend
    build:
        context: ./client
        dockerfile: Dockerfile
    volumes:
        - './client:/usr/app'
        - '/app/node_modules'
    ports:
        - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn start
        