version: '3.7'

services:
  app:
    container_name: poo-api-message
    image: maiconloure/nodepoo
    command: yarn dev
    ports:
      - "3333:3333"
    volumes:
      - .:/app
  
  web:
    container_name: poo-react-message
    build:
        context: ./frontend
        dockerfile: Dockerfile
    image: react-docker-app
    volumes:
        - './app'
        - '/app/node_modules'
    ports:
        - '3000:3000'
    environment:
        - NODE_ENV=development